### ISSUE TITLE
play command not working

### ISSUE THREAD

**Issue by bengm** [rkh/atom-sonic#3]
I cannot get the play command (ctrl-r) to work. Troubleshooting steps:
- sonic pi is running and cli is installed.
- sonic-pi-cli seems to be working fine. `sonic_pi play 70` or `sonic_pi run_command 'play 70'` both work fine from the command line.
- If I manually start a script in sonic pi, then go over to atom and run the ctrl-s command, it successfully stops playback.
- If I have a simple file (i.e. containing only `play 70`) and run the ctrl-r command, I get the success message within atom "Sent source code to Sonic Pi"; however, the sound does not play
- I did a bit more triage, but couldn't isolate the issue. I did a little debugging within the coffee code. The code snippet is being properly captured from atom and sent to the play() function... but I'm not familiar enough with the OSC portion to get in the middle of that.

Any help would be greatly appreciated.

Environment: Mac OSX 10.11.1; atom 1.1.0; Sonic Pi v2.7

PS: Thanks for making/sharing this plugin. I want to explore sonic pi more, but get frustrated w/ the built-in editor.

**Comment by bengm** [comment]
I did a bit more digging this morning, comparing it to the CLI tool. I found that this worked for me. https://github.com/rkh/atom-sonic/compare/master...bengm:master

**Comment by d3v-null** [comment]
I'm having the exact same problem which is fixed by @bengm 's patch
